---
name: Acceptenace Tests
on:
  workflow_dispatch: {}
  push:
    branches:
    - master
    paths:
    - '.github/workflows/acceptance-tests.yml'
    - '*.yaml'
    - 'test/**'
defaults:
  run:
    shell: bash
jobs:
  acceptance-test:
    uses: ./.github/workflows/acceptance-test-run.yml
    with:
      region: us-east-1
      tests: '*'
      deletion-policy: delete
      failure-policy: rollback
